name: Makefile CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install dependencies
      run: make Install

    - name: Build Docs
      run: make html

    - name: Run run
      run: make run
